# Generated by Django 2.1.7 on 2019-02-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etiquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_nota', models.CharField(max_length=256)),
                ('Nombre_cliente', models.CharField(max_length=256)),
                ('Telefono', models.CharField(max_length=256)),
                ('Fecha_recibido', models.CharField(max_length=256)),
                ('Equipo', models.CharField(max_length=256)),
                ('Trabajo', models.CharField(max_length=256)),
                ('Quien_Trabajara_El_Equipo', models.CharField(max_length=256)),
                ('Prende', models.CharField(max_length=256)),
                ('Tiene_chip_o_Sd', models.CharField(max_length=256)),
                ('Apagado', models.CharField(max_length=256)),
                ('Crack', models.CharField(max_length=256)),
                ('Descripcion_Del_Equipo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='juana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('edad', models.CharField(max_length=256)),
                ('estatura', models.CharField(max_length=256)),
                ('nacionalidad', models.CharField(max_length=256)),
                ('equipo', models.CharField(max_length=256)),
                ('universidad', models.CharField(max_length=256)),
                ('posicion', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lalala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('edad', models.CharField(max_length=256)),
                ('estatura', models.CharField(max_length=256)),
                ('nacionalidad', models.CharField(max_length=256)),
                ('equipo', models.CharField(max_length=256)),
                ('universidad', models.CharField(max_length=256)),
                ('posicion', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='mamma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('edad', models.CharField(max_length=256)),
                ('estatura', models.CharField(max_length=256)),
                ('nacionalidad', models.CharField(max_length=256)),
                ('equipo', models.CharField(max_length=256)),
                ('universidad', models.CharField(max_length=256)),
                ('posicion', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='terminados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_nota_T', models.CharField(max_length=256)),
                ('Nombre_cliente_T', models.CharField(max_length=256)),
                ('Fecha_Entrega_T', models.CharField(max_length=256)),
                ('Terminado_T', models.CharField(max_length=256)),
            ],
        ),
    ]
