# Generated by Django 2.1.7 on 2019-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiquetas',
            old_name='Apagado',
            new_name='Entrego_Apagado',
        ),
        migrations.AlterField(
            model_name='etiquetas',
            name='Fecha_recibido',
            field=models.DateField(max_length=256),
        ),
    ]
